[project]
name = "moku-go"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "moku>=3.3.3",
    "zeroconf>=0.147.0",
]
